This APT is simply a sum of products, where the product = [factor forecast]*[exposure or Factor loading]

The exposures are standardized: they have mean of zero and unit standard deviation.
    
What does this mean? That an average stock will have a factor exposure of zero. 

Also, a stock is primarily exposed to its industry (we can think of this as another factor!)

So, AT&T (for example) has an expected return of 6% due to its industry plus the SUMPRODUCT of its factors (factor forecast * factor exposure)

Also, a stock is primarily exposed to its industry (we can think of this as another factor!)

Finally, note the CAPM is essentially a single factor model: beta * [equity risk premium = market risk factor]

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as si

In [2]:
# Factor Forecasts (Risk_Premia)
Growth_Risk_Premium = 0.02
Bond_Risk_Premium = 0.025
Size_Risk_Premium = -0.015
ROE_Risk_Premium = 0.0
Market_Risk_Premium = 0.06
RF = 0.06

In [3]:
Stock = ['Amex','AT&T','Chevron','Coca-Cola','Disney','Dow']
Industry = ['FinServices','Telephones','Energy','Food','Entertain','Chemical']
Risk_Free_Rate = [RF, RF, RF, RF, RF, RF]
Growth_Beta = [0.17, -0.16, -0.53, -0.02, 0.13, -0.64]
Bond_Beta = [-0.05, 0.74, -0.24, 0.03, -0.86, -0.92]
Size_Beta = [0.19, 1.47, 0.83, 1.41, 0.71, 0.48]
ROE_Beta = [-0.28, -0.59, -0.72, 1.48, 0.42, 0.22]
Market_Beta = [1.16, 0.84, 0.7, 1.06, 1.13, 1.13]

In [4]:
df = pd.DataFrame({"Stock": Stock, "Industry":Industry, "Risk_Free_Rate":Risk_Free_Rate,
                   "Growth_Beta":Growth_Beta, "Bond_Beta":Bond_Beta, "Size_Beta":Size_Beta,
                   "ROE_Beta":ROE_Beta,"Market_Beta":Market_Beta})
df

,Stock,Industry,Risk_Free_Rate,Growth_Beta,Bond_Beta,Size_Beta,ROE_Beta,Market_Beta
0,Amex,FinServices,0.06,0.17,-0.05,0.19,-0.28,1.16
1,AT&T,Telephones,0.06,-0.16,0.74,1.47,-0.59,0.84
2,Chevron,Energy,0.06,-0.53,-0.24,0.83,-0.72,0.70
3,Coca-Cola,Food,0.06,-0.02,0.03,1.41,1.48,1.06
4,Disney,Entertain,0.06,0.13,-0.86,0.71,0.42,1.13
5,Dow,Chemical,0.06,-0.64,-0.92,0.48,0.22,1.13

In [5]:
APT = []
for i in range(0,len(Stock)):
    APT.append(RF + Growth_Beta[i] * Growth_Risk_Premium + Bond_Beta[i] * Bond_Risk_Premium 
               + Size_Beta[i] * Size_Risk_Premium + ROE_Beta[i] * ROE_Risk_Premium)
APT

[0.0593,
 0.05324999999999999,
 0.030950000000000002,
 0.0392,
 0.030449999999999998,
 0.016999999999999994]

In [6]:
CAPM = []
for i in range(0,len(Stock)):
    CAPM.append(RF + Market_Beta[i] * Market_Risk_Premium)
CAPM

[0.1296, 0.1104, 0.102, 0.1236, 0.12779999999999997, 0.12779999999999997]

In [7]:
df2 = pd.DataFrame({"APT": APT, "CAPM":CAPM})
df2

       APT    CAPM
0  0.05930  0.1296
1  0.05325  0.1104
2  0.03095  0.1020
3  0.03920  0.1236
4  0.03045  0.1278
5  0.01700  0.1278

In [8]:
df3 = pd.concat([df, df2], axis=1)
df3

,Stock,Industry,Risk_Free_Rate,Growth_Beta,Bond_Beta,Size_Beta,ROE_Beta,Market_Beta,APT,CAPM
0,Amex,FinServices,0.06,0.17,-0.05,0.19,-0.28,1.16,0.05930,0.1296
1,AT&T,Telephones,0.06,-0.16,0.74,1.47,-0.59,0.84,0.05325,0.1104
2,Chevron,Energy,0.06,-0.53,-0.24,0.83,-0.72,0.70,0.03095,0.1020
3,Coca-Cola,Food,0.06,-0.02,0.03,1.41,1.48,1.06,0.03920,0.1236
4,Disney,Entertain,0.06,0.13,-0.86,0.71,0.42,1.13,0.03045,0.1278
5,Dow,Chemical,0.06,-0.64,-0.92,0.48,0.22,1.13,0.01700,0.1278

In [9]:
df3['APT-CAPM']=df3['APT']-df3['CAPM']

In [10]:
df3

,Stock,Industry,Risk_Free_Rate,Growth_Beta,Bond_Beta,Size_Beta,ROE_Beta,Market_Beta,APT,CAPM,APT-CAPM
0,Amex,FinServices,0.06,0.17,-0.05,0.19,-0.28,1.16,0.05930,0.1296,-0.07030
1,AT&T,Telephones,0.06,-0.16,0.74,1.47,-0.59,0.84,0.05325,0.1104,-0.05715
2,Chevron,Energy,0.06,-0.53,-0.24,0.83,-0.72,0.70,0.03095,0.1020,-0.07105
3,Coca-Cola,Food,0.06,-0.02,0.03,1.41,1.48,1.06,0.03920,0.1236,-0.08440
4,Disney,Entertain,0.06,0.13,-0.86,0.71,0.42,1.13,0.03045,0.1278,-0.09735
5,Dow,Chemical,0.06,-0.64,-0.92,0.48,0.22,1.13,0.01700,0.1278,-0.11080